name: One-shot Deploy

on:
  workflow_dispatch:
    inputs:
      titulo:
        description: "Título do PR"
        required: true
        type: string
      codigo:
        description: "Cole instruções (--rm) e blocos de código"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@users.noreply.github.com"

      - id: branch
        run: |
          BRANCH="one-shot-$(date +%s)"
          git checkout -b "$BRANCH"
          echo "name=$BRANCH" >> "$GITHUB_OUTPUT"

      - name: Processar instruções
        run: |
          cat > input.txt <<'END_INPUT'
          ${{ github.event.inputs.codigo }}
          END_INPUT

          python3 <<'PY'
          import os, re, textwrap, time, mimetypes, subprocess, pathlib, sys

          txt = open("input.txt").read()

          # 1. Remover arquivos listados com '--rm caminho'
          for line in txt.splitlines():
              if line.strip().startswith("--rm "):
                  path = line.strip()[5:]
                  if os.path.exists(path):
                      subprocess.run(["git", "rm", "-f", path], check=True)
                      print("Removido", path)
                  else:
                      print("Aviso: arquivo não encontrado →", path, file=sys.stderr)

          # 2. Criar/atualizar arquivos a partir dos blocos ```
          patterns = [
              r'```(\w+)\s+([\w\-/\.]+)\n(.*?)```',      # caminho + quebra
              r'```(\w+)\n([\w\-/\.]+)\n(.*?)```',       # caminho na 2ª linha
              r'```(\w+)\s+([\w\-/\.]+)\s+(.*?)```',     # tudo na mesma linha
              r'```(\w+)\n(.*?)```'                      # sem caminho
          ]

          count = 0
          for pat in patterns:
              for m in re.findall(pat, txt, re.DOTALL):
                  lang, path, code = (m if len(m)==3 else (m[0], None, m[1]))
                  if not path:
                      ext = mimetypes.guess_extension(f"text/{lang}") or ".txt"
                      path = f"src/code-{int(time.time())}-{count}{ext}"

                  pathlib.Path(path).parent.mkdir(parents=True, exist_ok=True)
                  with open(path, "w") as f:
                      f.write(textwrap.dedent(code).strip() + "\n")
                  print("Criado/atualizado", path)
                  count += 1

          if count == 0:
              open("no-changes.txt", "w").write("Nenhum bloco de código válido recebido.\n")
          PY

          rm input.txt

      - id: diff
        run: |
          git add -A
          if [ -z "$(git status --porcelain)" ]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            git commit -m "${{ github.event.inputs.titulo }}"
            git push origin "${{ steps.branch.outputs.name }}"
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - if: steps.diff.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "${{ github.event.inputs.titulo }}" \
            --body "One-shot Deploy" \
            --base main \
            --head "${{ steps.branch.outputs.name }}"

      - if: steps.diff.outputs.changed == 'false'
        run: echo "Nada a fazer — PR não criado."
