name: Code Distribution

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'Descrição das mudanças'
        required: true
        type: string
      final_batch:
        description: 'É a última parte?'
        required: false
        type: boolean
        default: false
      files_json:
        description: 'JSON com arquivos e códigos'
        required: true
        type: string

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Code Bot"
          
      - name: Create branch
        run: |
          DESC="${{ github.event.inputs.description }}"
          BRANCH="feature/$(echo "$DESC" | tr ' ' '-' | tr '[:upper:]' '[:lower:]')"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          git checkout -b $BRANCH || git checkout $BRANCH
          
      - name: Process files
        run: |
          echo '${{ github.event.inputs.files_json }}' > files.json
          python3 -c "
          import json
          import os
          with open('files.json') as f:
              data = json.load(f)
          for path, content in data.items():
              os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
              with open(path, 'w') as f:
                  f.write(content)
              print(f'Created: {path}')
          "
          
      - name: Commit and push
        run: |
          git add .
          git commit -m "${{ github.event.inputs.description }}" || echo "No changes"
          git push origin $BRANCH
          
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}
          title: "${{ github.event.inputs.description }}"
          body: "Automated code distribution"
