name: Create LP from Structured Brief

on:
  issues:
    types: [opened]

jobs:
  create-lp-from-brief:
    if: startsWith(github.event.issue.title, '[LP]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Extract brief info
        id: extract
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.issue.title;
            const body = context.payload.issue.body || '';
            const match = title.match(/\[LP\]\s*(.+?)\s*-\s*(.+)/);
            if (!match) {
              throw new Error('Formato de título inválido. Use: [LP] cliente - nome-da-lp');
            }
            const cliente = match[1].trim().toLowerCase().replace(/[^a-z0-9]/g, '-');
            const lp = match[2].trim().toLowerCase().replace(/[^a-z0-9]/g, '-');
            const slug = `${cliente}-${lp}`;
            core.setOutput('cliente', cliente);
            core.setOutput('lp_nome', lp);
            core.setOutput('slug', slug);
            core.setOutput('brief', body);
            core.setOutput('branch', `lp-${slug}-${Date.now()}`);

      - name: Generate LP JSON
        run: |
          SLUG="${{ steps.extract.outputs.slug }}"
          BRIEF_CONTENT="${{ steps.extract.outputs.brief }}"
          npx ts-node scripts/process-brief.ts
        env:
          SLUG: ${{ steps.extract.outputs.slug }}
          BRIEF_CONTENT: ${{ steps.extract.outputs.brief }}

      - name: Create README
        run: |
          SLUG="${{ steps.extract.outputs.slug }}"
          mkdir -p lps/${SLUG}
          cat > lps/${SLUG}/README.md <<EOF2
          # Landing Page - ${SLUG}
          Criada automaticamente via Issue #${{ github.event.issue.number }}
          EOF2

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: add LP ${{ steps.extract.outputs.slug }}"
          title: "Nova LP: ${{ steps.extract.outputs.slug }}"
          body: |
            Landing page gerada automaticamente da Issue #${{ github.event.issue.number }}
          branch: ${{ steps.extract.outputs.branch }}
          delete-branch: true
          labels: |
            landing-page
            automated
            v3

      - name: Comment on Issue
        uses: actions/github-script@v6
        with:
          script: |
            const pr = "${{ steps.cpr.outputs.pull-request-url }}";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: pr ? `LP criada em ${pr}` : 'Erro ao criar PR'
            });
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });

