name: Deploy Code from Claude

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Titulo do PR'
        required: true
        type: string
      code_content:
        description: 'Codigo do Claude'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create branch and files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          BRANCH="claude-${{ github.run_number }}"
          git checkout -b $BRANCH
          
          echo "${{ github.event.inputs.code_content }}" > temp.txt
          
          git add .
          git commit -m "${{ github.event.inputs.title }}"
          git push origin $BRANCH
          
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: claude-${{ github.run_number }}
          title: ${{ github.event.inputs.title }}
          body: |
            Codigo do Claude deployado
